// templates/svelte/js/base/src/lib/NebulaBar.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { barPlugin } from "./function/nebulaPlugins";
    import type { Nebula } from "../types";

    export let nebula: Nebula;
    export let fields: string[];
    export let app: EngineAPI.IApp;

    let element: HTMLDivElement;

    onMount(async () => {
        await nebula.render({
            element: element,
            type: "bar",
            fields: fields,
            plugins: [barPlugin],
            properties: {
                title: "Nebula",
            },
        });
    });
</script>

<div class="container">
    <div class="object" bind:this={element} />
</div>

<style>
    .container {
        width: 100%;
        height: 600px;
    }

    .object {
        width: 100%;
        height: 600px;
        display: flex;
        margin-top: 30px;
    }
</style>

// templates/angular/ts/base/src/app/nebulabar/nebulabar.component.ts
import { Component, Input, OnInit } from "@angular/core";
import type { NebulaChart } from "../types";

@Component({
  selector: "nebulabar",
  templateUrl: "./nebulabar.component.html",
  styleUrls: ["./nebulabar.component.css"],
})
export class NebulaBarComponent implements OnInit {
  @Input() nebula: NebulaChart;
  @Input() app: EngineAPI.IApp;

  constructor() {}

  viz = {
    type: "bar",
    properties: {
      title: "Nebula",
    },
    style: {
      width: "100%",
      height: "600px",
      display: "flex",
      marginTop: "30px",
    },
  };

  ngOnInit(): void {}
}

<div class="container">
  <h1>Starter Project</h1>
  <nebula
    [nebula]="nebula"
    [properties]="viz.properties"
    [type]="viz.type"
    [style]="viz.style"
  ></nebula>
</div>
