// templates/react/ts/base/src/components/NebulaSelection.tsx
import { FC, useEffect, useRef } from "react";
import type { NebulaChart } from "../types";

const NebulaSelection: FC<{ nebula: NebulaChart }> = ({ nebula }) => {
    const elementRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!nebula) return;
        const run = async () => {
            (await nebula.selections()).mount(elementRef.current!);
        };
        run();
    }, [nebula]);

    return <div ref={elementRef}></div>;
};

export default NebulaSelection;

// templates/solid/ts/base/src/components/NebulaSelection.tsx
import { onMount } from "solid-js";
import type { QlikEntity } from "../types";

const NebulaSelection = (props: QlikEntity) => {
    let elementRef!: HTMLDivElement;
    const { nebula, app } = props;

    onMount(() => {
        const run = async () => {
            (await nebula.selections()).mount(elementRef);
        };
        run();
    });

    return <div ref={elementRef}></div>;
};

export default NebulaSelection;
