// templates/react/ts/base/src/components/NebulaSelection.tsx
import { FC, useEffect, useRef } from "react";
import type { NebulaChart } from "../types";

const NebulaSelection: FC<{ nebula: NebulaChart }> = ({ nebula }) => {
    const elementRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        if (!nebula) return;
        const run = async () => {
            (await nebula.selections()).mount(elementRef.current!);
        };
        run();
    }, [nebula]);

    return <div className="toolbar" ref={elementRef}></div>;
};

export default NebulaSelection;

// templates/svelte/ts/base/src/lib/components/NebulaSelection.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import type { NebulaChart } from "../../types";

    export let nebula: NebulaChart;

    let element: HTMLDivElement;

    onMount(async () => {
        (await nebula.selections()).mount(element);
    });
</script>

<div class="toolbar" bind:this={element} />
