// templates/vue/ts/base/src/components/NebulaSelection.vue
<script lang="ts">
import { PropType } from "vue";
import type { NebulaChart } from "../types";

export default {
    name: "NebulaSelection",
    components: {},
    props: {
        nebula: { type: Object as PropType<NebulaChart>, default: {} },
    },
    async mounted() {
        (await this.nebula.selections()).mount(this.$refs.element);
    },
};
</script>

<template>
    <div class="toolbar" ref="element"></div>
</template>

// templates/svelte/ts/base/src/lib/components/NebulaSelection.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import type { NebulaChart } from "../../types";

    export let nebula: NebulaChart;

    let element: HTMLDivElement;

    onMount(async () => {
        (await nebula.selections()).mount(element);
    });
</script>

<div class="toolbar" bind:this={element} />
