// templates/svelte/ts/enterprise/src/App.svelte
<script lang="ts">
    import enigma from "enigma.js";
    import schema from "enigma.js/schemas/12.67.2.json";
    import { QlikEnterpriseConnection } from "./lib/util/qlik-enterprise-connection";
    import { config } from "./config.sample";
    import { NebulaCharts } from "./lib/util/nebulaCharts";
    import NebulaBar from "./lib/components/NebulaBar.svelte";
    import Spinnner from "./lib/ui/spinnner.svelte";
    import type { NebulaChart } from "./types";
    import NebulaSelection from "./lib/components/NebulaSelection.svelte";

    let qlikInstance: EngineAPI.IApp;

    const qlik: QlikEnterpriseConnection = new QlikEnterpriseConnection(config.host, config.virtualProxy, enigma, schema);

    const establishConnection = async (): Promise<NebulaChart> => {
        qlikInstance = await qlik.connectAndOpenDoc(config.appId);
        const nebulaComponent = new NebulaCharts(qlik.app);
        return nebulaComponent.chart();
    };
</script>

<main>
    {#await establishConnection()}
        <Spinnner />
    {:then nebulaInstance}
        <NebulaSelection nebula={nebulaInstance} />
        <NebulaBar nebula={nebulaInstance} app={qlikInstance} />
    {/await}
</main>

<style>
    @import "../global.css";
    :root {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
    }
    main {
        text-align: center;
        padding: 1em;
        margin: 0 auto;
    }
</style>

// templates/vue/ts/enterprise/src/App.vue
<script lang="ts">
import NebulaBar from "./components/NebulaBar.vue";
import enigma from "enigma.js";
import schema from "enigma.js/schemas/12.67.2.json";
import { NebulaCharts } from "./util/nebulaCharts";
import NebulaSelection from "./components/NebulaSelection.vue";
import { QlikEnterpriseConnection } from "./util/qlik-enterprise-connection";
import Spinnner from "./ui/spinner.vue";
import type { NebulaChart } from "./types";
import { config } from "./config.sample";
import "../global.css";

const qlik: QlikEnterpriseConnection = new QlikEnterpriseConnection(config.host, config.virtualProxy, enigma, schema);

export default {
    name: "App",
    components: {
        Spinnner,
        NebulaBar,
        NebulaSelection,
    },
    props: [],
    data() {
        return {
            isLoading: <boolean>true,
            nebulaInstance: <NebulaChart>{},
            qlikInstance: <EngineAPI.IApp>{},
        };
    },

    async mounted() {
        const establishConnection = async (): Promise<NebulaChart> => {
            this.qlikInstance = await qlik.connectAndOpenDoc(config.appId);

            const nebulaComponent = new NebulaCharts(qlik.app);
            return nebulaComponent.chart();
        };

        this.nebulaInstance = await establishConnection();
        this.isLoading = false;
    },
};
</script>

<template>
    <main>
        <div v-if="isLoading">
            <Spinnner />
        </div>
        <div v-else>
            <NebulaSelection :nebula="nebulaInstance" />
            <NebulaBar :nebula="nebulaInstance" :app="qlikInstance" />
        </div>
    </main>
</template>

<style scoped>
main {
    text-align: center;
    padding: 1em;
    margin: 0 auto;
}
</style>
